version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'java-exam.com -> http://host.docker.internal:8080'
      STAGE: 'production'
      # STAGE: 'local'
      # FORCE_RENEW: 'true'
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
    volumes:
      - https-portal-data:/var/lib/https-portal
      - ./conf.d/.htpasswd:/etc/nginx/.htpasswd
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  https-portal-data:
