version: '3'
services:
  testing:
    image: eclipse-temurin:25-jdk-alpine
    working_dir: /app
    expose:
      - 8080
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=testing

  prod:
    image: java-exam-v2
    expose:
      - 8081
    volumes:
      - ./java-exam-prod.db:/app/java-exam-prod.db
    working_dir: /app

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'everyone:engineer@team1.java-exam.com.35.213.80.42.nip.io -> http://testing:8080,
                everyone:engineer@test-team1.java-exam.com.35.213.80.42.nip.io -> http://prod:8081'
      STAGE: 'staging'
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - testing
      - prod
volumes:
  https-portal-data:
